name: release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-release:
    name: upload release to pypi
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install build

      - name: build
        run: python -m build

      - name: upload
        uses: pypa/gh-action-pypi-publish@release/v1